(VDB-1233) Median storage mappings
makerdao/vdb-mcd-transformers pull request #156
Opened 2020-04-13 14:02 UTC by Gslaughl

2020-04-20 20:25 UTC, elizabethengelman requested changes
Looks good to me, though we'll need to update the migration timestamp for the bud migration, and add a new migration for changing the other medianizer storage table names.

2020-04-20 20:25 UTC, elizabethengelman commented on db/migrations/20200310230012_create_medianizer_storage_table.sql
> +CREATE TABLE maker.median_val
I think we'll probably want to create a new migration for this change, instead of updating this one.

2020-04-20 20:25 UTC, elizabethengelman commented on transformers/component_tests/median/configured_transformer_test.go
> +var _ = Describe("Executing the flip transformer", func() {
`:%s/flip/median`

2020-04-20 20:25 UTC, elizabethengelman commented on db/migrations/20200406160236_create_median_bud_storage_table.sql
> +    a          INTEGER NOT NULL REFERENCES addresses (id) ON DELETE CASCADE,
Though on second thought, the events we're looking at for bud addresses seem to use `a`.

2020-05-15 00:14 UTC, yaoandrew commented
Changes merged into #155

2020-05-15 00:14 UTC, closed without merging